### ISSUE TITLE
Error in downloading [Bug Report]

### ISSUE THREAD

**Issue by nandometzger** [apple/ARKitScenes#63]
Hi I noticed that the variable 'splits' is not defined anywhere in your 'download_data.py'

running:

```
python3 download_data.py upsampling --download_dir .../ARkitScenes --split Validation --video_id_csv depth_upsampling/upsampling_train_val_splits.csv 
```

yields error
```
...
...
Downloading file /home/nandometzger/data/ARkitScenes/upsampling/Validation/48458667.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53.7M  100 53.7M    0     0  18.1M      0  0:00:02  0:00:02 --:--:-- 18.1M
Unzipping zip file /home/nandometzger/data/ARkitScenes/upsampling/Validation/48458667.zip
Traceback (most recent call last):
  File "/home/nandometzger/misc/ARKitScenes/download_data.py", line 273, in <module>
    download_data(args.dataset,
  File "/home/nandometzger/misc/ARKitScenes/download_data.py", line 202, in download_data
    if dataset == 'upsampling' and VALIDATION in splits:
NameError: name 'splits' is not defined

```

**Comment by arik1089** [comment]
Pushed a fix to this error. 

Thanks @nandometzger for your help.

**Comment by nandometzger** [comment]
Thank you for the prompt fix!
